<?php

// Generated by the up.time SVG Dashboard Generator
// uptime software 2012
// author: Joel Pereira


// verify which dashboard we'll be loading
if (isset($_REQUEST['d'])) {
	$svgName = $_REQUEST['d'];
	$svgFileName = "saved/{$svgName}.svg";
	// check if the dashboard exists
	if ( ! file_exists($svgFileName) ) {
		print "Dashboard '{$svgName}' does not exist.<br/>";
		exit(2);
	}
}
else {
	// no dashboard specified, so error out
	print "No dashboard specified<br/>";
	print "Make sure to add \"?d=DASHBOARDNAME\" to the end of this page's URL.\n";
	exit(1);
}

// Include the Smarty header file
require_once("smarty_header.php");


$svgContent = file_get_contents($svgFileName);


////////////////////////////////////////////////////////////////////////////////////////////
// SMARTY: Assign variables
$smarty->assign( 'svgContent', $svgContent );
// SMARTY: Display page
$smarty->display('view_dashboard.tpl');

?>

